vich_uploader:
    db_driver: orm

    mappings:
       image_article:
           uri_prefix: /img
           upload_destination: '%kernel.project_dir%/public/img'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
 
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true